const Joi = require('joi');

const roadmapValidation = {
  // Generate AI roadmap validation
  generateRoadmap: Joi.object({
    additionalInstructions: Joi.string()
      .max(1000)
      .allow('')
      .messages({
        'string.max': 'Additional instructions cannot exceed 1000 characters'
      })
  }),

  // Create manual roadmap validation
  createRoadmap: Joi.object({
    totalWeeks: Joi.number()
      .integer()
      .min(1)
      .max(52)
      .required()
      .messages({
        'number.base': 'Total weeks must be a number',
        'number.min': 'Total weeks must be at least 1',
        'number.max': 'Total weeks cannot exceed 52',
        'any.required': 'Total weeks is required'
      }),

    generatedBy: Joi.string()
      .valid('manual', 'ai', 'template')
      .default('manual')
      .messages({
        'any.only': 'Generated by must be one of: manual, ai, template'
      }),

    weeks: Joi.array()
      .items(
        Joi.object({
          weekNumber: Joi.number().integer().min(1).required(),
          title: Joi.string().min(3).max(200).required(),
          objectives: Joi.array().items(Joi.string().max(500)).max(10),
          milestone: Joi.string().max(300).allow(''),
          tasks: Joi.array().items(
            Joi.object({
              title: Joi.string().min(3).max(200).required(),
              description: Joi.string().min(10).required(),
              type: Joi.string().valid('lecture', 'exercise', 'project', 'quiz', 'reading', 'video', 'other').default('exercise'),
              difficulty: Joi.string().valid('easy', 'medium', 'hard', 'expert').default('medium'),
              estimatedHours: Joi.number().min(0.5).max(100).default(5),
              orderIndex: Joi.number().integer().min(1).default(1),
              acceptanceCriteria: Joi.array().items(Joi.string().max(500)).max(10),
              deliverable: Joi.string().max(500)
            })
          )
        })
      )
  }),

  // Update roadmap validation
  updateRoadmap: Joi.object({
    totalWeeks: Joi.number()
      .integer()
      .min(1)
      .max(52)
      .messages({
        'number.base': 'Total weeks must be a number',
        'number.min': 'Total weeks must be at least 1',
        'number.max': 'Total weeks cannot exceed 52'
      }),

    adaptationLevel: Joi.string()
      .valid('base', 'adapted_once', 'adapted_multiple')
      .messages({
        'any.only': 'Adaptation level must be one of: base, adapted_once, adapted_multiple'
      })
  }).min(1).messages({
    'object.min': 'At least one field must be provided for update'
  }),

  // Add week validation
  addWeek: Joi.object({
    weekNumber: Joi.number()
      .integer()
      .min(1)
      .max(52)
      .required()
      .messages({
        'number.base': 'Week number must be a number',
        'number.min': 'Week number must be at least 1',
        'number.max': 'Week number cannot exceed 52',
        'any.required': 'Week number is required'
      }),

    title: Joi.string()
      .min(3)
      .max(200)
      .required()
      .messages({
        'string.empty': 'Week title is required',
        'string.min': 'Week title must be at least 3 characters',
        'string.max': 'Week title cannot exceed 200 characters'
      }),

    objectives: Joi.array()
      .items(Joi.string().max(500))
      .max(10)
      .messages({
        'array.max': 'Cannot have more than 10 objectives',
        'string.max': 'Each objective cannot exceed 500 characters'
      }),

    milestone: Joi.string()
      .max(300)
      .allow('')
      .messages({
        'string.max': 'Milestone cannot exceed 300 characters'
      })
  }),

  // Update week validation
  updateWeek: Joi.object({
    weekNumber: Joi.number()
      .integer()
      .min(1)
      .max(52),

    title: Joi.string()
      .min(3)
      .max(200),

    objectives: Joi.array()
      .items(Joi.string().max(500))
      .max(10),

    milestone: Joi.string()
      .max(300)
      .allow('')
  }).min(1).messages({
    'object.min': 'At least one field must be provided for update'
  }),

  // Add task validation
  addTask: Joi.object({
    title: Joi.string()
      .min(3)
      .max(200)
      .required()
      .messages({
        'string.empty': 'Task title is required',
        'string.min': 'Task title must be at least 3 characters',
        'string.max': 'Task title cannot exceed 200 characters'
      }),

    description: Joi.string()
      .min(10)
      .required()
      .messages({
        'string.empty': 'Task description is required',
        'string.min': 'Description must be at least 10 characters'
      }),

    type: Joi.string()
      .valid('lecture', 'exercise', 'project', 'quiz', 'reading', 'video', 'other')
      .default('exercise')
      .messages({
        'any.only': 'Type must be one of: lecture, exercise, project, quiz, reading, video, other'
      }),

    difficulty: Joi.string()
      .valid('easy', 'medium', 'hard', 'expert')
      .default('medium')
      .messages({
        'any.only': 'Difficulty must be one of: easy, medium, hard, expert'
      }),

    estimatedHours: Joi.number()
      .min(0.5)
      .max(100)
      .default(5)
      .messages({
        'number.base': 'Estimated hours must be a number',
        'number.min': 'Estimated hours must be at least 0.5',
        'number.max': 'Estimated hours cannot exceed 100'
      }),

    orderIndex: Joi.number()
      .integer()
      .min(1)
      .default(1)
      .messages({
        'number.base': 'Order index must be a number',
        'number.min': 'Order index must be at least 1'
      }),

    acceptanceCriteria: Joi.array()
      .items(Joi.string().max(500))
      .max(10)
      .messages({
        'array.max': 'Cannot have more than 10 acceptance criteria',
        'string.max': 'Each criterion cannot exceed 500 characters'
      }),

    deliverable: Joi.string()
      .max(500)
      .messages({
        'string.max': 'Deliverable description cannot exceed 500 characters'
      }),

    resources: Joi.array()
      .items(
        Joi.object({
          type: Joi.string().valid('link', 'document', 'video', 'tool').required(),
          title: Joi.string().min(3).max(200).required(),
          url: Joi.string().uri().required(),
          description: Joi.string().max(500).allow('')
        })
      )
      .max(10)
  }),

  // Update task validation
  updateTask: Joi.object({
    title: Joi.string()
      .min(3)
      .max(200),

    description: Joi.string()
      .min(10),

    type: Joi.string()
      .valid('lecture', 'exercise', 'project', 'quiz', 'reading', 'video', 'other'),

    difficulty: Joi.string()
      .valid('easy', 'medium', 'hard', 'expert'),

    estimatedHours: Joi.number()
      .min(0.5)
      .max(100),

    orderIndex: Joi.number()
      .integer()
      .min(1),

    acceptanceCriteria: Joi.array()
      .items(Joi.string().max(500))
      .max(10),

    deliverable: Joi.string()
      .max(500)
  }).min(1).messages({
    'object.min': 'At least one field must be provided for update'
  })
};

module.exports = roadmapValidation;
